### ISSUE TITLE
Add feature to keep track of 'active' pdfurls

### ISSUE THREAD

**Issue by Ivraj** [HarvardOpenData/propublica-data#9]
There is the possible edge case that a pdfurl for a manual entry changes. It's most likely the case that Propublica has replaced it with an auto version. However, in our current system, hypothetically if a manual entry is replaced by a link for another manual entry, the manual data that was gathered for the initial entry would be lost. In an ideal scenario, the user would have an opportunity to copy the manual entry from the old sheet into the new manual entry. 

In order to facilitate this, we would need to keep track of all of the manual pdfurls that come back from API calls and see if there are any left over from `get_existing_data` that weren't used. At the end of the script, these entries would be put in the bottom of the spreadsheet and the user would be warned about their presence. 

Since I think this situation is not terribly likely, this is definitely not a high priority.

**Comment by Ivraj** [comment]
Oh lit, I didn't even see that you already added this. Correct me if I'm wrong though, the script in its current from removes the data for the outdated pdfurls, right? Should we have some way of preserving those? It might be worth piping them to another file like `outdated.csv` or something so that the user can copy and paste the old data. Or would that not be as helpful? Your thoughts @jdhe1120 ?

**Comment by jdhe1120** [comment]
yeah i did! so the script pops out everything that's used which means anything that remains are the outdated pdfurls + the manual #s inputted for those pdfs, we could indeed pipe it to an outdated.csv!

**Comment by jdhe1120** [comment]
done! to test the feature change one of the manualpdfurls in the input file to anything random
